// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clientStructure.proto

package transport

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Client struct {
	Id                   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string         `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Country              string         `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Inbox                []*Client_Mail `protobuf:"bytes,5,rep,name=inbox,proto3" json:"inbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_f89aedaff266c504, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Client) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Client) GetInbox() []*Client_Mail {
	if m != nil {
		return m.Inbox
	}
	return nil
}

type Client_Mail struct {
	RemoteEmail          string   `protobuf:"bytes,1,opt,name=remoteEmail,proto3" json:"remoteEmail,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client_Mail) Reset()         { *m = Client_Mail{} }
func (m *Client_Mail) String() string { return proto.CompactTextString(m) }
func (*Client_Mail) ProtoMessage()    {}
func (*Client_Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_f89aedaff266c504, []int{0, 0}
}

func (m *Client_Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client_Mail.Unmarshal(m, b)
}
func (m *Client_Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client_Mail.Marshal(b, m, deterministic)
}
func (m *Client_Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client_Mail.Merge(m, src)
}
func (m *Client_Mail) XXX_Size() int {
	return xxx_messageInfo_Client_Mail.Size(m)
}
func (m *Client_Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_Client_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_Client_Mail proto.InternalMessageInfo

func (m *Client_Mail) GetRemoteEmail() string {
	if m != nil {
		return m.RemoteEmail
	}
	return ""
}

func (m *Client_Mail) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Client)(nil), "transport.Client")
	proto.RegisterType((*Client_Mail)(nil), "transport.Client.Mail")
}

func init() { proto.RegisterFile("clientStructure.proto", fileDescriptor_f89aedaff266c504) }

var fileDescriptor_f89aedaff266c504 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x8a, 0xc3, 0x30,
	0x10, 0x44, 0x91, 0x6d, 0xf9, 0xf0, 0x1a, 0xae, 0x58, 0xee, 0x0e, 0x71, 0x95, 0x48, 0xe5, 0x22,
	0xa8, 0x48, 0xda, 0x74, 0x21, 0x65, 0x1a, 0xe7, 0x0b, 0x64, 0x5b, 0x85, 0xc0, 0x96, 0x8c, 0xb2,
	0x86, 0xf8, 0x0f, 0xf3, 0x59, 0xc1, 0x32, 0x0e, 0xe9, 0x66, 0x86, 0x61, 0xdf, 0x2c, 0xfc, 0xb6,
	0xbd, 0x35, 0x8e, 0x6e, 0x14, 0xa6, 0x96, 0xa6, 0x60, 0xd4, 0x18, 0x3c, 0x79, 0x2c, 0x28, 0x68,
	0x77, 0x1f, 0x7d, 0xa0, 0xdd, 0x93, 0x41, 0x7e, 0x8e, 0x25, 0xfc, 0x86, 0xc4, 0x76, 0x82, 0x49,
	0x56, 0xf1, 0x3a, 0xb1, 0x1d, 0x22, 0x64, 0x4e, 0x0f, 0x46, 0x24, 0x92, 0x55, 0x45, 0x1d, 0x35,
	0xfe, 0x00, 0x37, 0x83, 0xb6, 0xbd, 0x48, 0x63, 0xb8, 0x1a, 0x14, 0xf0, 0xd5, 0xfa, 0xc9, 0x51,
	0x98, 0x45, 0x16, 0xf3, 0xcd, 0xe2, 0x1e, 0xb8, 0x75, 0x8d, 0x7f, 0x08, 0x2e, 0xd3, 0xaa, 0x3c,
	0xfc, 0xa9, 0x37, 0x59, 0xad, 0x54, 0x75, 0xd5, 0xb6, 0xaf, 0xd7, 0xd2, 0xff, 0x09, 0xb2, 0xc5,
	0xa2, 0x84, 0x32, 0x98, 0xc1, 0x93, 0xb9, 0x44, 0x16, 0x8b, 0x37, 0x3f, 0xa3, 0x65, 0x5b, 0xe3,
	0xbb, 0x79, 0xdb, 0xb6, 0xe8, 0x26, 0x8f, 0xcf, 0x1d, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x73,
	0xfe, 0xaa, 0x36, 0xf5, 0x00, 0x00, 0x00,
}
