version: "3.3"
services:
  api:
    container_name: "testsd.go"
    build: "./api"
    ports:
      - "8080:8080"
    volumes:
      - "./testsd.go:/go/src/appdatatemp/"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27100:27017"
