// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32            `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	SocialFollowers      *SocialFollowers `protobuf:"bytes,3,opt,name=socialFollowers,proto3" json:"socialFollowers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetSocialFollowers() *SocialFollowers {
	if m != nil {
		return m.SocialFollowers
	}
	return nil
}

type SocialFollowers struct {
	Youtube              int32    `protobuf:"varint,1,opt,name=youtube,proto3" json:"youtube,omitempty"`
	Twitter              int32    `protobuf:"varint,2,opt,name=twitter,proto3" json:"twitter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialFollowers) Reset()         { *m = SocialFollowers{} }
func (m *SocialFollowers) String() string { return proto.CompactTextString(m) }
func (*SocialFollowers) ProtoMessage()    {}
func (*SocialFollowers) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *SocialFollowers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialFollowers.Unmarshal(m, b)
}
func (m *SocialFollowers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialFollowers.Marshal(b, m, deterministic)
}
func (m *SocialFollowers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialFollowers.Merge(m, src)
}
func (m *SocialFollowers) XXX_Size() int {
	return xxx_messageInfo_SocialFollowers.Size(m)
}
func (m *SocialFollowers) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialFollowers.DiscardUnknown(m)
}

var xxx_messageInfo_SocialFollowers proto.InternalMessageInfo

func (m *SocialFollowers) GetYoutube() int32 {
	if m != nil {
		return m.Youtube
	}
	return 0
}

func (m *SocialFollowers) GetTwitter() int32 {
	if m != nil {
		return m.Twitter
	}
	return 0
}

func init() {
	proto.RegisterType((*Person)(nil), "main.Person")
	proto.RegisterType((*SocialFollowers)(nil), "main.SocialFollowers")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xca,
	0xe7, 0x62, 0x0b, 0x00, 0x8b, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0x89, 0xe9, 0xa9, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0xac, 0x41, 0x20, 0xa6, 0x90, 0x3d, 0x17, 0x7f, 0x71, 0x7e, 0x72, 0x66, 0x62, 0x8e,
	0x5b, 0x7e, 0x4e, 0x4e, 0x7e, 0x79, 0x6a, 0x51, 0xb1, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0xb7, 0x91,
	0xa8, 0x1e, 0xc8, 0x3c, 0xbd, 0x60, 0x54, 0xc9, 0x20, 0x74, 0xd5, 0x4a, 0xae, 0x5c, 0xfc, 0x68,
	0x6a, 0x84, 0x24, 0xb8, 0xd8, 0x2b, 0xf3, 0x4b, 0x4b, 0x4a, 0x93, 0x20, 0x96, 0xb3, 0x06, 0xc1,
	0xb8, 0x20, 0x99, 0x92, 0xf2, 0xcc, 0x92, 0x92, 0xd4, 0x22, 0xa8, 0x1b, 0x60, 0xdc, 0x24, 0x36,
	0xb0, 0x27, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x78, 0x96, 0x1b, 0xc9, 0xd4, 0x00, 0x00,
	0x00,
}
